title: LearnDesk
iconURL: assets/open-book.png
theme: jekyll-theme-leaf
permalink: :slug

social:
  twitter: sayeekrish
  github: sayeekrish

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 1058
google_analytics: 171253985